export enum MedicalMeasureTypesEnum {
    SIZE = "SIZE",
    WEIGHT = "WEIGHT",
    TEMPERATURE = "TEMPERATURE",
    RESPIRATORY_FREQUENCY = "RESPIRATORY_FREQUENCY",
    OXIMETRY = "OXIMETRY",
    MUSCLE_MASS_INDEX = "MUSCLE_MASS_INDEX",
    GLICEMY = "GLICEMY"
}